spring:
  application:
    name: consumer

  datasource:
    url: jdbc:mysql://localhost:3306/mailer
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GOOGLE_EMAIL_ADDRESS}
    password: ${GOOGLE_EMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8081