spring:
  application:
    name: consumer

  datasource:
    url: jdbc:mysql://localhost:3306/mailer
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: update